version: '3.9'
services:
  api:  
    image: tjrdnjs1534/devkor:0.0
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres  
    env_file:
      - .env
  postgres:
    image: postgres
    ports: 
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=$DB_USER 
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE